name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: webanalytics_user
          POSTGRES_USER: webanalytics_user
          POSTGRES_PASSWORD: password123
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PYTHONPATH: backend/webanalytics
      DEBUG: "False"
      SECRET_KEY: "testing-secret-key"
      DJANGO_SETTINGS_MODULE: backend.webanalytics.settings
      DATABASE_URL: postgres://webanalytics_user:password123@localhost:5432/webanalytics

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/webanalytics/requirements.txt

      - name: Run tests with pytest
        working-directory: backend/webanalytics
        run: |
          pytest

      - name: Run ruff (linter)
        run: |
          pip install ruff
          ruff .
