name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: webanalytics
          POSTGRES_USER: webuser
          POSTGRES_PASSWORD: password
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: "False"
      SECRET_KEY: "testing-secret-key"
      DATABASE_URL: postgres://webuser:password@localhost:5432/webanalytics

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          pytest

      - name: Run ruff (linter)
        run: |
          pip install ruff
          ruff .

      - name: Run pycodestyle
        run: |
          pip install pycodestyle
          pycodestyle .

      - name: Run pydocstyle
        run: |
          pip install pydocstyle
          pydocstyle .
